jobs:
- name: Run-Tests
  plan:
  - in_parallel:
      steps:
      - get: github-repo
        tags:
        - ((REGIONS))
        trigger: true
      - get: nodejs
        tags:
        - ((REGIONS))
  - task: ui-tests
    file: github-repo/((TEST_RUN_TASK_FILE))
    tags:
      - ((REGIONS))
    image: nodejs
    params:
      AUTH_URL: ((NPM_CLIENT_BASIC_AUTH_URL))
      REGISTRY_PASS: ((registry_pw))
      REGISTRY_URL: ((NODE_PULL_URL))
      REGISTRY_USER: ((registry_user))
      SH_ENV_TYPE: ((SH_ENV_TYPE))
resources:
- name: github-repo
  type: git
  tags:
    - ((REGIONS))
  source: &repo-source
    uri: ((GITHUB_URL))
    access_token: ((github_deploy_token))
    private_key: ((github-deploy-key.private_key))
    repo: ((GIT_REPO))
    branch: ((BRANCH))
    api_endpoint: ((GIT_API_END_POINT))
- name: nodejs
  type: docker-image
  tags:
    - ((REGIONS))
  source:
    username: ((registry_user))
    password: ((registry_pw))
    repository: ((private_registry_url))/((BUILD_IMAGE_PATH))
    tag: ((NODE_TAG))
